package ca.sfu.cmpt362.ayusharora.stressmeter.imagerequest

import android.content.Context
import android.media.MediaPlayer
import android.os.Build
import android.os.VibrationEffect
import android.os.Vibrator
import androidx.annotation.RequiresApi
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.ViewModel
import ca.sfu.cmpt362.ayusharora.stressmeter.R

// To preserve the state of UI elements
class ImageRequestViewModel : ViewModel() {

    // Resource images stored in int arrays (3 different sets)
    private val images1 = intArrayOf(
        R.drawable.set1_0, R.drawable.set1_1, R.drawable.set1_2, R.drawable.set1_3,
        R.drawable.set1_4, R.drawable.set1_5, R.drawable.set1_6, R.drawable.set1_7,
        R.drawable.set1_8, R.drawable.set1_9, R.drawable.set1_10, R.drawable.set1_11,
        R.drawable.set1_12, R.drawable.set1_13, R.drawable.set1_14, R.drawable.set1_15
    )
    private val images2 = intArrayOf(
        R.drawable.set2_0, R.drawable.set2_1, R.drawable.set2_2, R.drawable.set2_3,
        R.drawable.set2_4, R.drawable.set2_5, R.drawable.set2_6, R.drawable.set2_7,
        R.drawable.set2_8, R.drawable.set2_9, R.drawable.set2_10, R.drawable.set2_11,
        R.drawable.set2_12, R.drawable.set2_13, R.drawable.set2_14, R.drawable.set2_15
    )
    private val images3 = intArrayOf(
        R.drawable.set3_0, R.drawable.set3_1, R.drawable.set3_2, R.drawable.set3_3,
        R.drawable.set3_4, R.drawable.set3_5, R.drawable.set3_6, R.drawable.set3_7,
        R.drawable.set3_8, R.drawable.set3_9, R.drawable.set3_10, R.drawable.set3_11,
        R.drawable.set3_12, R.drawable.set3_13, R.drawable.set3_14, R.drawable.set3_15
    )

    // Array of images currently being displayed in the GridView
    val currentImages = MutableLiveData<IntArray?>()

    // To know which set is currently being displayed
    private var currentSet = 1

    // To play background music
    var mediaPlayer: MediaPlayer? = null

    // To vibrate the phone
    var vibrator: Vibrator? = null


    // IMAGES
    // Load images when activity/fragment is initialized or created
    fun initializeImages() {
        if (currentImages.value == null){
            images1.shuffle()
            currentImages.value = images1
            }
    }

    // Helper method to load new images based on current image set being displayed
    fun loadNextImageSet() {

        var imagesToShow: IntArray? = null
        when (currentSet){
            1->{
                currentSet = 2
                imagesToShow = images2
            }
            2->{
                currentSet = 3
                imagesToShow = images3
            }
            3->{
                currentSet = 1
                imagesToShow = images1
            }
        }

        imagesToShow?.shuffle()
        currentImages.value = imagesToShow
    }

    // Load music to MediaPlayer and start playing
    // Learnt it from https://developer.android.com/media/platform/mediaplayer/basics
    fun startMusic (context: Context, resource: Int ) {
        if (mediaPlayer == null) {
            mediaPlayer = MediaPlayer.create(context, resource)
            mediaPlayer?.isLooping = true
        }
        mediaPlayer?.start()
    }

    // Start vibrating the phone
    // Learnt it from https://developer.android.com/reference/android/os/Vibrator
    // The @RequireApi tag is autogenerated by android studio
    @RequiresApi(Build.VERSION_CODES.O)
    fun startVibration(context: Context) {
        if (vibrator == null) {
            vibrator = context.getSystemService(Context.VIBRATOR_SERVICE) as Vibrator
        }
        val pattern = longArrayOf(0, 500, 500)
        val effect = VibrationEffect.createWaveform(pattern, 0)
        vibrator?.vibrate(effect)
    }

}
