package ca.sfu.cmpt362.ayusharora.stressmeter.imagerequest

import android.content.Intent
import android.os.Build
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.GridView
import androidx.annotation.RequiresApi
import androidx.fragment.app.Fragment
import androidx.lifecycle.ViewModelProvider
import ca.sfu.cmpt362.ayusharora.stressmeter.R
import ca.sfu.cmpt362.ayusharora.stressmeter.databinding.FragmentImageRequestBinding
import ca.sfu.cmpt362.ayusharora.stressmeter.imageresponse.ImageResponse
class ImageRequestFragment : Fragment() {

    // Binding class given by default android studio code
    private var _binding: FragmentImageRequestBinding? = null

    private val binding get() = _binding!!

    // View model to preserve UI elements
    private lateinit var imageRequestViewModel: ImageRequestViewModel

    // To load images to GridView
    private lateinit var imageAdapter: ImageAdapter

    // Added my helper methods to the default function written by android studio
    // The @RequireAPI tag is auto-generated by android studio
    @RequiresApi(Build.VERSION_CODES.O)
    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View {

        _binding = FragmentImageRequestBinding.inflate(inflater, container, false)
        val root: View = binding.root

        imageRequestViewModel = ViewModelProvider(requireActivity())[ImageRequestViewModel::class.java]

        imageRequestViewModel.currentImages.observe(viewLifecycleOwner) { images ->
            imageAdapter.updateImages(images)
        }

        loadMusic()
        setupGridView()
        handleButtonClick()

        return root
    }

    override fun onDestroyView() {

        super.onDestroyView()
        _binding = null
    }

    // Resumes the state of music and vibration when this fragment is resumed
    // The @RequireAPI tag is auto-generated by android studio
    @RequiresApi(Build.VERSION_CODES.O)
    override fun onResume() {
        super.onResume()
        imageRequestViewModel.resumeMusic()
        imageRequestViewModel.startVibration(requireContext())
    }

    // Pauses the music and vibration when this fragment is paused
    override fun onPause() {
        super.onPause()
        imageRequestViewModel.pauseMusic()
        imageRequestViewModel.stopVibration()
    }

    // Helper method to setup images in a GridView
    // The images are loaded in the ImageRequestViewModel Class itself
    // Adapter does the actual work of assigning each image in an image array to the gridView
    // Click on each image opens a new activity (ImageResponse)
    private fun setupGridView(){

        val gridView: GridView = binding.imageRequestGridview
        imageRequestViewModel.initializeImages()
        imageAdapter = ImageAdapter(requireContext(), imageRequestViewModel.currentImages.value)
        gridView.adapter = imageAdapter
        gridView.setOnItemClickListener { parent, view, position, id ->
            val intent = Intent(requireActivity(), ImageResponse::class.java)
            val selectedImage = imageAdapter.getItem(position) as Int
            intent.putExtra("selectedImage", selectedImage)
            startActivity(intent)
        }
    }

    // Helper method to initialize the sound elements (mediaPlayer and vibrator)
    // The @RequireAPI tag is auto-generated by android studio
    @RequiresApi(Build.VERSION_CODES.O)
    private fun loadMusic(){
        imageRequestViewModel.startMusic(requireContext(), R.raw.harry_potter_theme_1)
        imageRequestViewModel.startVibration(requireContext())
    }

    // Helper method to override button clicks
    // The logic of loading new images is inside the ImageRequestViewModel class
    private fun handleButtonClick () {

        val button = binding.imageRequestButtonMoreImages
        button.setOnClickListener {
            imageRequestViewModel.loadNextImageSet()
        }
    }
}